In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
date = {
    "Alina": [60, 165, True],
    "Bogdan": [72, 183, False],
    "Ciprian": [69, 178, False],
    "Diana": [55, 152, True],
    "Elena": [58, 168, True],
    "Andrei": [80, 185, False],
    "Mihai": [75, 177, False],
    "Irina": [62, 170, True],
    "Florin": [90, 190, False],
    "Maria": [53, 160, True],
    "Vlad": [70, 175, False],
    "Ioana": [50, 155, True],
    "Radu": [68, 172, False],
    "Ana": [59, 162, True],
    "George": [85, 182, False],
    "Larisa": [61, 167, True],
    "Stefan": [78, 180, False],
    "Bianca": [56, 158, True],
    "Paul": [74, 176, False],
    "Oana": [54, 163, True],
    "Cosmin": [82, 188, False],
    "Teodora": [57, 159, True],
    "Ionut": [76, 181, False],
    "Gabriela": [60, 164, True]
}

In [4]:
pd.DataFrame(date)

,Alina,Bogdan,Ciprian,Diana,Elena,Andrei,Mihai,Irina,Florin,Maria,...,George,Larisa,Stefan,Bianca,Paul,Oana,Cosmin,Teodora,Ionut,Gabriela
0,60,72,69,55,58,80,75,62,90,53,...,85,61,78,56,74,54,82,57,76,60
1,165,183,178,152,168,185,177,170,190,160,...,182,167,180,158,176,163,188,159,181,164
2,True,False,False,True,True,False,False,True,False,True,...,False,True,False,True,False,True,False,True,False,True

In [5]:
pd.DataFrame(date).T

           0    1      2
Alina     60  165   True
Bogdan    72  183  False
Ciprian   69  178  False
Diana     55  152   True
Elena     58  168   True
Andrei    80  185  False
Mihai     75  177  False
Irina     62  170   True
Florin    90  190  False
Maria     53  160   True
Vlad      70  175  False
Ioana     50  155   True
Radu      68  172  False
Ana       59  162   True
George    85  182  False
Larisa    61  167   True
Stefan    78  180  False
Bianca    56  158   True
Paul      74  176  False
Oana      54  163   True
Cosmin    82  188  False
Teodora   57  159   True
Ionut     76  181  False
Gabriela  60  164   True

In [6]:
pd.DataFrame(date).transpose()

           0    1      2
Alina     60  165   True
Bogdan    72  183  False
Ciprian   69  178  False
Diana     55  152   True
Elena     58  168   True
Andrei    80  185  False
Mihai     75  177  False
Irina     62  170   True
Florin    90  190  False
Maria     53  160   True
Vlad      70  175  False
Ioana     50  155   True
Radu      68  172  False
Ana       59  162   True
George    85  182  False
Larisa    61  167   True
Stefan    78  180  False
Bianca    56  158   True
Paul      74  176  False
Oana      54  163   True
Cosmin    82  188  False
Teodora   57  159   True
Ionut     76  181  False
Gabriela  60  164   True

In [8]:
date.keys(), date.values()

(dict_keys(['Alina', 'Bogdan', 'Ciprian', 'Diana', 'Elena', 'Andrei', 'Mihai', 'Irina', 'Florin', 'Maria', 'Vlad', 'Ioana', 'Radu', 'Ana', 'George', 'Larisa', 'Stefan', 'Bianca', 'Paul', 'Oana', 'Cosmin', 'Teodora', 'Ionut', 'Gabriela']),
 dict_values([[60, 165, True], [72, 183, False], [69, 178, False], [55, 152, True], [58, 168, True], [80, 185, False], [75, 177, False], [62, 170, True], [90, 190, False], [53, 160, True], [70, 175, False], [50, 155, True], [68, 172, False], [59, 162, True], [85, 182, False], [61, 167, True], [78, 180, False], [56, 158, True], [74, 176, False], [54, 163, True], [82, 188, False], [57, 159, True], [76, 181, False], [60, 164, True]]))

In [11]:
df = pd.DataFrame(date.values(), index=date.keys(), columns=["Greutate", "Intaltime", "Voce_Subtire"])
df

          Greutate  Intaltime  Voce_Subtire
Alina           60        165          True
Bogdan          72        183         False
Ciprian         69        178         False
Diana           55        152          True
Elena           58        168          True
Andrei          80        185         False
Mihai           75        177         False
Irina           62        170          True
Florin          90        190         False
Maria           53        160          True
Vlad            70        175         False
Ioana           50        155          True
Radu            68        172         False
Ana             59        162          True
George          85        182         False
Larisa          61        167          True
Stefan          78        180         False
Bianca          56        158          True
Paul            74        176         False
Oana            54        163          True
Cosmin          82        188         False
Teodora         57        159          True
Ionut           76        181         False
Gabriela        60        164          True

In [12]:
df["Voce_Subtire"] = df["Voce_Subtire"].astype(int)
df

          Greutate  Intaltime  Voce_Subtire
Alina           60        165             1
Bogdan          72        183             0
Ciprian         69        178             0
Diana           55        152             1
Elena           58        168             1
Andrei          80        185             0
Mihai           75        177             0
Irina           62        170             1
Florin          90        190             0
Maria           53        160             1
Vlad            70        175             0
Ioana           50        155             1
Radu            68        172             0
Ana             59        162             1
George          85        182             0
Larisa          61        167             1
Stefan          78        180             0
Bianca          56        158             1
Paul            74        176             0
Oana            54        163             1
Cosmin          82        188             0
Teodora         57        159             1
Ionut           76        181             0
Gabriela        60        164             1

In [13]:
df["Gen"] = df["Voce_Subtire"].apply(lambda x: "feminin" if x else "masculin")
df.head()

         Greutate  Intaltime  Voce_Subtire       Gen
Alina          60        165             1   feminin
Bogdan         72        183             0  masculin
Ciprian        69        178             0  masculin
Diana          55        152             1   feminin
Elena          58        168             1   feminin